from __future__ import annotations

from typing import Any

from canisend.materials import ApplicationMaterials


SECTION_KEYS = {
    "research fit": "research_fit",
    "teaching fit": "teaching_fit",
    "departmental contribution": "departmental_contribution",
    "service and leadership": "service_leadership",
}


def build_cover_letter_content(parsed_job: dict[str, Any], materials: ApplicationMaterials) -> dict[str, Any]:
    sections = _markdown_sections(materials.cover_letter_draft)
    preamble = _clean_preamble(sections.get("_preamble", ""))
    return {
        "job": {
            "title": parsed_job["title"],
            "institution": parsed_job["institution"],
            "department": parsed_job["department"],
            "deadline": parsed_job["deadline"],
            "application_url": parsed_job["application_url"],
        },
        "recipient": {
            "start_title": "Dear Selection Committee,",
            "cl_title": f"Application for {parsed_job['title']}",
            "date": "",
            "department": _unknown_to_empty(parsed_job["department"]),
            "institution": _unknown_to_empty(parsed_job["institution"]),
            "address": "",
            "postcode": "",
        },
        "opening": preamble or f"I am writing to apply for the position of {parsed_job['title']} at {parsed_job['institution']}.",
        "sections": {
            "research_fit": _section_or_placeholder(sections, "research_fit", "Add evidence-based research fit."),
            "teaching_fit": _section_or_placeholder(sections, "teaching_fit", "Add evidence-based teaching fit."),
            "departmental_contribution": _section_or_placeholder(
                sections,
                "departmental_contribution",
                "Add department-specific contribution after reviewing the advert.",
            ),
            "service_leadership": _section_or_placeholder(
                sections,
                "service_leadership",
                "Add supported service or leadership evidence.",
            ),
        },
        "closing": "I would welcome the opportunity to discuss how my work fits the role.",
        "salutation": "Yours sincerely,",
    }


def build_application_package_content(parsed_job: dict[str, Any], materials: ApplicationMaterials, final_package: str) -> dict[str, Any]:
    return {
        "job": {
            "title": parsed_job["title"],
            "institution": parsed_job["institution"],
            "department": parsed_job["department"],
            "deadline": parsed_job["deadline"],
            "application_url": parsed_job["application_url"],
        },
        "fit_report": materials.fit_report,
        "cover_letter": materials.cover_letter_draft,
        "cv_tailoring_notes": materials.cv_tailoring_notes,
        "criteria_checklist": materials.criteria_checklist,
        "final_package": final_package,
    }


def render_modernpro_cover_letter_source(content: dict[str, Any]) -> str:
    return """// Generated by CanISend from structured cover_letter_content.json.
// Edit jobs/<job-slug>/03_cover_letter_draft.md or cover_letter_content.json before final rendering.
#import "@preview/fontawesome:0.6.0": *
#import "@preview/modernpro-coverletter:0.0.8": *

#let content = json("cover_letter_content.json")

#show: coverletter.with(
  font-type: "PT Serif",
  margin: (left: 2cm, right: 2cm, top: 3cm, bottom: 2cm),
  name: [Applicant Name],
  address: [],
  salutation: [#content.salutation],
  contacts: (),
  recipient: (
    start-title: [#content.recipient.start_title],
    cl-title: [#content.recipient.cl_title],
    date: [#content.recipient.date],
    department: [#content.recipient.department],
    institution: [#content.recipient.institution],
    address: [#content.recipient.address],
    postcode: [#content.recipient.postcode],
  ),
)

#content.opening

== Research Fit
#content.sections.research_fit

== Teaching Fit
#content.sections.teaching_fit

== Departmental Contribution
#content.sections.departmental_contribution

== Service and Leadership
#content.sections.service_leadership

#content.closing
"""


def render_modernpro_application_package_source() -> str:
    return """// Generated by CanISend from structured application_package_content.json.
#import "@preview/fontawesome:0.6.0": *
#import "@preview/modernpro-coverletter:0.0.8": *

#let package = json("application_package_content.json")

#show: statement.with(
  font-type: "PT Serif",
  margin: (left: 2cm, right: 2cm, top: 3cm, bottom: 2cm),
  name: [Applicant Name],
  address: [],
  contacts: (),
)

= Application Package

== Job Information
- Title: #package.job.title
- Institution: #package.job.institution
- Department: #package.job.department
- Deadline: #package.job.deadline
- Application URL: #package.job.application_url

== Fit Report
#package.fit_report

== Cover Letter Draft
#package.cover_letter

== CV Tailoring Notes
#package.cv_tailoring_notes

== Criteria Checklist
#package.criteria_checklist
"""


def _markdown_sections(markdown_text: str) -> dict[str, str]:
    current = "_preamble"
    sections: dict[str, list[str]] = {current: []}
    for raw_line in markdown_text.splitlines():
        line = raw_line.rstrip()
        if line.startswith("# "):
            continue
        if line.startswith("## "):
            current = SECTION_KEYS.get(line[3:].strip().lower(), line[3:].strip().lower().replace(" ", "_"))
            sections.setdefault(current, [])
            continue
        sections.setdefault(current, []).append(line)

    return {key: _clean_block("\n".join(lines)) for key, lines in sections.items()}


def _clean_preamble(value: str) -> str:
    lines = []
    for line in value.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.lower().startswith("dear "):
            continue
        if stripped.lower().startswith("yours sincerely"):
            continue
        if stripped == "[Applicant name]":
            continue
        lines.append(stripped)
    return "\n\n".join(lines)


def _clean_block(value: str) -> str:
    lines = []
    for line in value.splitlines():
        stripped = line.strip()
        if stripped.lower().startswith("yours sincerely"):
            break
        if stripped == "[Applicant name]":
            break
        lines.append(line.rstrip())
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return "\n".join(lines)


def _section_or_placeholder(sections: dict[str, str], key: str, placeholder: str) -> str:
    value = sections.get(key, "").strip()
    return value or f"[{placeholder}]"


def _unknown_to_empty(value: str) -> str:
    return "" if value == "unknown" else value
