from __future__ import annotations

from typing import Any

from canisend.materials import ApplicationMaterials


SECTION_KEYS = {
    "research fit": "research_fit",
    "teaching fit": "teaching_fit",
    "departmental contribution": "departmental_contribution",
    "service and leadership": "service_leadership",
}


def build_cover_letter_content(parsed_job: dict[str, Any], materials: ApplicationMaterials) -> dict[str, Any]:
    sections = _markdown_sections(materials.cover_letter_draft)
    preamble = _clean_preamble(sections.get("_preamble", ""))
    return {
        "job": {
            "title": parsed_job["title"],
            "institution": parsed_job["institution"],
            "department": parsed_job["department"],
            "deadline": parsed_job["deadline"],
            "application_url": parsed_job["application_url"],
        },
        "recipient": {
            "start_title": "Dear Selection Committee,",
            "cl_title": f"Application for {parsed_job['title']}",
            "date": "",
            "department": _unknown_to_empty(parsed_job["department"]),
            "institution": _unknown_to_empty(parsed_job["institution"]),
            "address": "",
            "postcode": "",
        },
        "opening": preamble or f"I am writing to apply for the position of {parsed_job['title']} at {parsed_job['institution']}.",
        "sections": {
            "research_fit": _section_or_placeholder(sections, "research_fit", "Add evidence-based research fit."),
            "teaching_fit": _section_or_placeholder(sections, "teaching_fit", "Add evidence-based teaching fit."),
            "departmental_contribution": _section_or_placeholder(
                sections,
                "departmental_contribution",
                "Add department-specific contribution after reviewing the advert.",
            ),
            "service_leadership": _section_or_placeholder(
                sections,
                "service_leadership",
                "Add supported service or leadership evidence.",
            ),
        },
        "closing": "I would welcome the opportunity to discuss how my work fits the role.",
        "salutation": "Yours sincerely,",
    }


def build_application_package_content(parsed_job: dict[str, Any], materials: ApplicationMaterials, final_package: str) -> dict[str, Any]:
    return {
        "job": {
            "title": parsed_job["title"],
            "institution": parsed_job["institution"],
            "department": parsed_job["department"],
            "deadline": parsed_job["deadline"],
            "application_url": parsed_job["application_url"],
        },
        "fit_report": materials.fit_report,
        "cover_letter": materials.cover_letter_draft,
        "cv_tailoring_notes": materials.cv_tailoring_notes,
        "criteria_checklist": materials.criteria_checklist,
        "final_package": final_package,
    }


def render_modernpro_cover_letter_source(content: dict[str, Any]) -> str:
    recipient = content["recipient"]
    sections = content["sections"]
    return f"""// Generated by CanISend as an editable Typst source.
// Edit this .typ file directly after reviewing evidence citations.
#import "@preview/fontawesome:0.6.0": *
#import "@preview/modernpro-coverletter:0.0.8": *

#show: coverletter.with(
  font-type: "PT Serif",
  margin: (left: 2cm, right: 2cm, top: 3cm, bottom: 2cm),
  name: [Applicant Name],
  address: [],
  salutation: [{typst_text(content["salutation"])}],
  contacts: (),
  recipient: (
    start-title: [{typst_text(recipient["start_title"])}],
    cl-title: [{typst_text(recipient["cl_title"])}],
    date: [{typst_text(recipient["date"])}],
    department: [{typst_text(recipient["department"])}],
    institution: [{typst_text(recipient["institution"])}],
    address: [{typst_text(recipient["address"])}],
    postcode: [{typst_text(recipient["postcode"])}],
  ),
)

// CANISEND: section opening
{markdown_to_typst(content["opening"])}

// CANISEND: section research_fit
== Research Fit
{markdown_to_typst(sections["research_fit"])}

// CANISEND: section teaching_fit
== Teaching Fit
{markdown_to_typst(sections["teaching_fit"])}

// CANISEND: section departmental_contribution
== Departmental Contribution
{markdown_to_typst(sections["departmental_contribution"])}

// CANISEND: section service_leadership
== Service and Leadership
{markdown_to_typst(sections["service_leadership"])}

// CANISEND: section closing
{markdown_to_typst(content["closing"])}
"""


def render_modernpro_application_package_source(content: dict[str, Any]) -> str:
    job = content["job"]
    return f"""// Generated by CanISend as an editable Typst source.
// Edit this .typ file directly after reviewing evidence citations.
#import "@preview/fontawesome:0.6.0": *
#import "@preview/modernpro-coverletter:0.0.8": *

#show: statement.with(
  font-type: "PT Serif",
  margin: (left: 2cm, right: 2cm, top: 3cm, bottom: 2cm),
  name: [Applicant Name],
  address: [],
  contacts: (),
)

= Application Package

// CANISEND: section job_information
== Job Information
- Title: {typst_text(job["title"])}
- Institution: {typst_text(job["institution"])}
- Department: {typst_text(job["department"])}
- Deadline: {typst_text(job["deadline"])}
- Application URL: {typst_text(job["application_url"])}

// CANISEND: section fit_report
== Fit Report
{markdown_to_typst(content["fit_report"])}

// CANISEND: section cover_letter
== Cover Letter Draft
{markdown_to_typst(content["cover_letter"])}

// CANISEND: section cv_tailoring_notes
== CV Tailoring Notes
{markdown_to_typst(content["cv_tailoring_notes"])}

// CANISEND: section criteria_checklist
== Criteria Checklist
{markdown_to_typst(content["criteria_checklist"])}
"""


def typst_text(value: str) -> str:
    return (
        str(value)
        .replace("\\", "\\\\")
        .replace("#", "\\#")
        .replace("$", "\\$")
        .replace("[", "\\[")
        .replace("]", "\\]")
    )


def markdown_to_typst(markdown_text: str) -> str:
    lines: list[str] = []
    for raw_line in markdown_text.splitlines():
        line = raw_line.rstrip()
        if line.startswith("### "):
            lines.append("=== " + typst_text(line[4:]))
        elif line.startswith("## "):
            lines.append("== " + typst_text(line[3:]))
        elif line.startswith("# "):
            lines.append("= " + typst_text(line[2:]))
        else:
            lines.append(typst_text(line))
    return "\n".join(lines).strip()


def _markdown_sections(markdown_text: str) -> dict[str, str]:
    current = "_preamble"
    sections: dict[str, list[str]] = {current: []}
    for raw_line in markdown_text.splitlines():
        line = raw_line.rstrip()
        if line.startswith("# "):
            continue
        if line.startswith("## "):
            current = SECTION_KEYS.get(line[3:].strip().lower(), line[3:].strip().lower().replace(" ", "_"))
            sections.setdefault(current, [])
            continue
        sections.setdefault(current, []).append(line)

    return {key: _clean_block("\n".join(lines)) for key, lines in sections.items()}


def _clean_preamble(value: str) -> str:
    lines = []
    for line in value.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.lower().startswith("dear "):
            continue
        if stripped.lower().startswith("yours sincerely"):
            continue
        if stripped == "[Applicant name]":
            continue
        lines.append(stripped)
    return "\n\n".join(lines)


def _clean_block(value: str) -> str:
    lines = []
    for line in value.splitlines():
        stripped = line.strip()
        if stripped.lower().startswith("yours sincerely"):
            break
        if stripped == "[Applicant name]":
            break
        lines.append(line.rstrip())
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return "\n".join(lines)


def _section_or_placeholder(sections: dict[str, str], key: str, placeholder: str) -> str:
    value = sections.get(key, "").strip()
    return value or f"[{placeholder}]"


def _unknown_to_empty(value: str) -> str:
    return "" if value == "unknown" else value
