# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: PengJiaxin.CanISend
PackageVersion: 0.7.0-alpha.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: canisend-0.7.0-alpha.1-x86_64-pc-windows-msvc\canisend.exe
  PortableCommandAlias: canisend
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/jxpeng98/CanISend/releases/download/v0.7.0-alpha.1/canisend-0.7.0-alpha.1-x86_64-pc-windows-msvc.zip
  InstallerSha256: a9b5ac290094dacc00c1b287704b764cfb98a5342ad81c2da7197de2e6c49ccd
ManifestType: installer
ManifestVersion: 1.10.0
