[package]
name = "canisend-gui"
description = "Tauri and Svelte desktop application for CanISend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true

[[bin]]
name = "canisend-gui"
path = "src/main.rs"

[features]
custom-protocol = ["tauri/custom-protocol"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
canisend-app = { path = "../canisend-app", version = "=1.0.0-alpha.5" }
canisend-cli = { path = "../canisend-cli", version = "=1.0.0-alpha.5" }
canisend-contracts = { path = "../canisend-contracts", version = "=1.0.0-alpha.5" }
serde.workspace = true
serde_json.workspace = true
tauri.workspace = true
tauri-plugin-dialog.workspace = true
tauri-plugin-window-state.workspace = true

[lints]
workspace = true
